aboutcars/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('web.urls')),
    path('admin/', admin.site.urls)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.contrib import admin
from django.urls import path
from web.views import *

urlpatterns = [
    path('', main_view, name='main'),
    path('home', main_view, name='main'),
    path('registration/', registration_view, name='registration'),
    path('auth/', auth_view, name='auth'),
    path('logout/', logout_view, name='logout'),
    path('cars/', cars_view, name='cars'),
    path('blog/', blog_view, name='blog'),
    path('post/<int:id>', post_view, name='post'),
    path('post/add', create_post_view, name='create_post'),
    path('post/<int:id>/edit', edit_post_view, name='edit_post'),
    path('post/<int:id>/delete', delete_post_view, name='delete_post'),
    path('car/add', add_car_view, name='add_car'),
    path('car/<int:id>', car_view, name='car'),
    path('car/<int:id>/edit', edit_car_view, name='edit_car'),
    path('car/<int:id>/delete', delete_car_view, name='delete_car'),
    path('analytics', analytics_view, name='analytics')
]

web/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class CarModel(models.Model):
    model = models.CharField(max_length=256)
    brand = models.CharField(max_length=256)

    def __str__(self):
        return f'{self.brand} {self.model}'


class Car(models.Model):
    year = models.IntegerField(verbose_name='Год производства')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Владелец')
    model = models.ForeignKey(CarModel, on_delete=models.SET_NULL, null=True, verbose_name='Марка, модель')
    image = models.ImageField(upload_to='car_images/', null=True, blank=True, verbose_name='Фото')


class Post(models.Model):
    title = models.CharField(max_length=256, verbose_name='Заголовок')
    text = models.TextField(verbose_name='Содержимое')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор')
    car = models.ForeignKey(Car, on_delete=models.CASCADE, verbose_name='Автомобиль')
    visits = models.IntegerField(default=0)

web/templates/web/addCar.html
{% extends 'web/base.html' %}
{% block content %}
    <h2>Добавить автомобиль</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Добавить</button>
    </form>
{% endblock %}

web/templates/web/analytics.html
{% extends 'web/base.html' %}
{% block content %}
    <h2>Статистика</h2>
    <p>
        <b>Кол-во пользователей:</b> {{ users_count }}
        <br>
        <b>Кол-во постов:</b> {{ posts_count }}
    </p>
{% endblock %}

web/templates/web/auth.html
{% extends 'web/base.html' %}
{% block content %}
<h2>Авторизация</h2>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Войти</button>
    </form>
{% endblock %}

web/templates/web/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About cars</title>
</head>
<body>
    <nav>
        <a href="{% url 'main'%}">Главная</a>
        {% if user.is_anonymous %}
            <a href="{% url 'registration' %}">Регистрация</a>
            <a href="{% url 'auth' %}">Авторизация</a>
        {% else %}
            <a href="{% url 'blog' %}">Мой блог</a>
            <a href="{% url 'cars' %}">Мои авто</a>
            <a href="{% url 'logout' %}">Выйти</a>
        {% endif %}
        <a href="{% url 'analytics' %}">Аналитика</a>
    </nav>
    <hr>
    {% block content %}{% endblock %}
</body>
</html>

web/templates/web/blog.html
{% extends 'web/base.html' %}
{% block content %}
    <h2>Мой блог</h2>
    <a href="{% url 'create_post' %}">Добавить пост</a>
    <ul>
        {% for post in posts %}
        <li>
            <a href="{% url 'post' post.id %}">{{ post.title }}</a>
        </li>
        {% endfor %}
    </ul>
{% endblock %}

web/templates/web/car.html
{% extends 'web/base.html' %}
{% block content %}
<h3>{{ car.model }}</h3>
<p>{{ car.year }}</p>
{% if car.image.url != None %}
<img src="{{car.image.url}}" style="height:200px">
{% endif %}
<br>
{% if is_owner %}
<a href="{% url 'edit_car' car.id %}">Редактировать</a>
<a href="{% url 'delete_car' car.id %}">Удалить</a>
{% endif %}
{% endblock %}

web/templates/web/cars.html
{% extends 'web/base.html' %}
{% block content %}
    <h2>Мои автомобили</h2>
    <a href="{% url 'add_car' %}">Добавить автомобиль</a>
    <ul>
        {% for car in cars %}
        <li>
            <a href="{% url 'car' car.id %}">{{ car.model }}</a>
        </li>
        {% endfor %}
    </ul>
{% endblock %}

web/templates/web/createPost.html
{% extends 'web/base.html' %}
{% block content %}
    <h2>Создание записи в блог</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <select name="car" required id="id_car">
            <option value="" selected>Авто</option>
            {% for car in cars %}
                <option value="{{ car.id }}">{{car.model}}</option>
            {% endfor %}
        </select>
        <button>Создать</button>
    </form>
{% endblock %}

web/templates/web/editCar.html
{% extends 'web/base.html' %}
{% block content %}
    <h2>Редактировать автомобиль</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Обновить</button>
    </form>
{% endblock %}

web/templates/web/editPost.html
{% extends 'web/base.html' %}
{% block content %}
    <h2>Редактировать пост</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <select name="car" required id="id_car">
            <option value="{{ selected_car.id }}" selected>{{ selected_car.model }}</option>
            {% for car in cars %}
                {% if car.id != selected_car.id %}
                    <option value="{{ car.id }}">{{car.model}}</option>
                {% endif %}
            {% endfor %}
        </select>
        <button>Обновить</button>
    </form>
{% endblock %}

web/templates/web/main.html
{% extends 'web/base.html' %}
{% block content %}
    {% if not user.is_anonymous %}
        Привет, {{ user.username }}
    {% endif %}
    <ul>
        {% for post in posts %}
            <li>
                <a href="{% url 'post' post.id %}">{{ post.title }} | {{ post.user.username }} | {{ post.car.model }}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

web/templates/web/post.html
{% extends 'web/base.html' %}
{% block content %}
<h3>{{ post.title }}</h3>
<p>{{ post.text }}</p>
<p>{{ post.car.model }}</p>
<br>
{% if is_author %}
<a href="{% url 'edit_post' post.id %}">Редактировать</a>
<a href="{% url 'delete_post' post.id %}">Удалить</a>
<br>
<b>Кол-во просмотров:</b> {{ post.visits }} <!-- Статистика по просмотрам -->
{% endif %}
{% endblock %}

web/templates/web/registration.html
{% extends 'web/base.html' %}
{% block content %}
    <h2>Регистрация</h2>
    {% if is_success %}
        <p>Спасибо за регистрацию)</p>
    {% else %}
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button>Зарегистрироваться</button>
        </form>
    {% endif %}
{% endblock %}